# Generated by Django 4.2.7 on 2023-11-20 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='exp_date',
        ),
        migrations.AddField(
            model_name='product',
            name='type',
            field=models.CharField(choices=[('Mobile Phone', 'Mobile Phone'), ('Tablet', 'Tablet'), ('Smart watch', 'Smart watch'), ('Laptop', 'Laptop')], default='Mobile Phone', max_length=100),
        ),
    ]
